version: '3'
services:        
    registryprod:
        #build:
        #    dockerfile: ./registry/registry.dockerfile
        #    context: .
        image: registry:2
        container_name: registryprod
        restart: always
        ports:
            - 5001:5000
        volumes:
            - /var/registry/prod:/var/lib/registry
        environment:
            REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
            REGISTRY_HTTP_TLS_KEY: /certs/domain.key              
            #VIRTUAL_HOST: localhost
            #VIRTUAL_PROTO: https
            #VIRTUAL_PORT: 5000        #environment:
        #    REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
            #REGISTRY_AUTH: htpasswd
            #REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
            #REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm   
        #deploy:
        #    resources:
        #        limits:
        #            cpus: '0.50'
        #            memory: 50M
        #        reservations:
        #            cpus: '0.10'
        #            memory: 20M     
        networks: 
            - devops-cloud-prod

networks: 
    devops-cloud-prod:
        driver: bridge                        
