version: '3'
services:        
    registryhom:
        #build:
        #    dockerfile: ./registry/registry.dockerfile
        #    context: .
        image: registry:2
        container_name: registryhom
        restart: always
        ports:
            - 5000:5000          
        volumes:
            - /var/registry/homolog:/var/lib/registry
            - /var/registry/certs:/certs
        environment:
            REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
            REGISTRY_HTTP_TLS_KEY: /certs/domain.key              
            #VIRTUAL_HOST: localhost
            #VIRTUAL_PROTO: https
            #VIRTUAL_PORT: 5000
            #REGISTRY_AUTH: htpasswd
            #REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
            #REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm              
        #deploy:
        #    resources:
        #        limits:
        #            cpus: '0.50'
        #            memory: 50M
        #        reservations:
        #            cpus: '0.10'
        #            memory: 20M 
        networks: 
            - devops-cloud-hom

networks: 
    devops-cloud-hom:
        driver: bridge                        
