version: '3'
services:        
    registry:
        image: registry:2
        container_name: registry
        restart: always
        ports:
            - 5000:5000
        volumes:
            - /var/registry:/var/lib/registry
        resources:
            limits:
                memory: 128mi
                cpus: "0.5"            
        #environment:
            #VIRTUAL_HOST: localhost
            #VIRTUAL_PROTO: https
            #VIRTUAL_PORT: 5000
            #REGISTRY_HTTP_TLS_CERTIFICATE: /etc/letsencrypt/live/docker.domain.com/fullchain.pem
            #REGISTRY_HTTP_TLS_KEY: /etc/letsencrypt/live/docker.domain.com/privkey.pem
            #REGISTRY_AUTH: htpasswd
            #REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
            #REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm