version: '3'
services:        
    nginx:
        image: nginx:1.9
        container_name: nginx
        ports:
            - 5043:443
        links:
            - registry:registry
        volumes:
            - ./nginx/:/etc/nginx/conf.d
        networks: 
            - devops-cloud

    registry:
        build:
            dockerfile: ./registry/registry.dockerfile
            context: .
        image: phoenix4go/registry:2.1
        container_name: registry
        restart: always
        ports:
            - 5000:5000
        #environment:
        #    REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
        volumes:
            - /var/registry:/var/lib/registry
            #- /home/diegolirio/workspace/docker/cloud-devops/registry:/etc/docker
        #insecure-registry: p4go-devops.southindia.cloudapp.azure.com:5000

        #deploy:
        #    resources:
        #        limits:
        #            cpus: '0.50'
        #            memory: 50M
        #        reservations:
        #            cpus: '0.10'
        #            memory: 20M 
              
        #environment:
            #VIRTUAL_HOST: localhost
            #VIRTUAL_PROTO: https
            #VIRTUAL_PORT: 5000
            #REGISTRY_HTTP_TLS_CERTIFICATE: /etc/letsencrypt/live/docker.domain.com/fullchain.pem
            #REGISTRY_HTTP_TLS_KEY: /etc/letsencrypt/live/docker.domain.com/privkey.pem
            #REGISTRY_AUTH: htpasswd
            #REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
            #REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm

        networks: 
            - devops-cloud

networks: 
    devops-cloud:
        driver: bridge                        
